leftnav:
- identifier: bb583173-719d-4ff2-b846-4b540c1396b4
  name: The Ugly truth
  pageRef: /pages/only-page
  weight: 10
- identifier: ace1647a-834c-4da7-b509-8ffdaafe73c3
  name: Unugly
  pageRef: /resources/sample-local-pdf_pdf
  parent: bb583173-719d-4ff2-b846-4b540c1396b4
  weight: 10
